### PR TITLE
DNM: Trackable benchmarking for CQRRP

### PR DESCRIPTION
**Pull request by rileyjmurray**
DNM = Do not merge.

I'll commit results from experiments here as well.

### CODE REVIEW

**Comment by TeachRaccooon** [comment]
@rileyjmurray I got a failure when running GPU benchmarks locally on Elephant, screenshot below.
Any idea why this might be happening?
I presume that this failure did not show up on your machine.
image

**Review by rileyjmurray — COMMENTED** [review]
Why is this commit on the do-not-merge benchmarking branch?

**Review by rileyjmurray — COMMENTED** [review]
I looked at commit https://github.com/BallisticLA/RandLAPACK/pull/84/commits/bb3d0e98cba768b3ea4d4b55baa61218a3b2955b.

Why are these changes on this do-not-merge benchmarking branch? Seems like they're applicable more broadly.

**Comment by TeachRaccooon** [comment]
Closing per switch to a new branch.

**Pull request closed without merging**
