### PR TITLE
Update BLAS++ and LAPACK++ links.

### PR DESCRIPTION
**Pull request by TeachRaccooon**
Libraries migrated to github.

### CODE REVIEW

**Comment by TeachRaccooon** [comment]
@burlen do you have an intuition behind why the build is failing here? All i added was updated links for blas++ and lapack++.

**Comment by burlen** [comment]
I assume that once you rebase from main things will be fine. I'll see if there's a setting in github to make this clear. If things still fail after you do that, I'll take a closer look.

**Comment by burlen** [comment]
yes, there is a setting, and it was not on. I enabled it and now github will tell you when you are out of date.

**Comment by TeachRaccooon** [comment]
Looks like all checks are passing now, thanks! All in favor of merging?

**Pull request merged**
